// app/src/models/user.model.ts
import { DataTypes, Model, Optional } from "sequelize";
import { hashPassword } from "../utils/hash";
import sequelize from "../config/database";

/**
 * Defines the roles available for application users.
 */
export type UserRole = "admin" | "request_manager";

/**
 * Represents the attributes of a user.
 */
export interface UserAttributes {
  /** Unique identifier of the user. */
  id: number;

  /** Full name of the user. */
  name: string;

  /** Unique email address used by the user. */
  email: string;

  /** Hashed password of the user. */
  password: string;

  /** Role assigned to the user. */
  role: UserRole;
}

/**
 * Defines the attributes required when creating a new user.
 *
 * The `id` attribute is optional because it is automatically generated
 * by the database.
 */
export interface UserCreationAttributes extends Optional<UserAttributes, "id" > { }

/**
 * Sequelize model representing an application user.
 */
export class User extends Model<UserAttributes, UserCreationAttributes>
  implements UserAttributes {
  /** Unique identifier of the user. */
  public id!: number;

  /** Full name of the user. */
  public name!: string;

  /** Unique email address of the user. */
  public email!: string;

  /** Hashed password of the user. */
  public password!: string;

  /** Role assigned to the user. */
  public role!: UserRole;
}

/**
 * Initializes the User model and defines its database configuration.
 *
 * The model is mapped to the `users` table and uses underscored column
 * names and automatic timestamps.
 *
 * Passwords are automatically hashed before a user is created or when
 * an existing user's password is modified.
 */
User.init(
  {
    /**
     * Primary key of the user.
     * Automatically generated by the database.
     */
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },

    /**
     * Full name of the user.
     */
    name: {
      type: DataTypes.STRING(100),
      allowNull: false,
      validate: {
        notEmpty: true,
      },
    },

    /**
     * Unique email address of the user.
     */
    email: {
      type: DataTypes.STRING(150),
      allowNull: false,
      unique: true,
      validate: {
        isEmail: true,
      },
    },

    /**
     * Hashed password stored for the user.
     */
    password: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },

    /**
     * Role assigned to the user.
     */
    role: {
      type: DataTypes.ENUM("admin", "request_manager"),
      allowNull: false,
      defaultValue: "user",
    },
  },
  {
    sequelize,
    tableName: "users",
    underscored: true,
    timestamps: true,

    /**
     * Sequelize hooks used to hash user passwords automatically.
     */
    hooks: {
      /**
       * Hashes the user's password before creating a new user.
       */
      beforeCreate: async (user: User) => {
        if (user.password) {
          user.password = await hashPassword(user.password);
        }
      },

      /**
       * Hashes the user's password before updating the user when
       * the password has been changed.
       */
      beforeUpdate: async (user: User) => {
        if (user.changed("password")) {
          user.password = await hashPassword(user.password as string);
        }
      },
    },
  }
);

export default User;
